In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
import tensorflow as tf

In [26]:
data = pd.read_csv("train.csv")
X = data.iloc[:,[1,2,5,6,7,8,9,10]] 
# [[2202 2075]
#  [   0    0]]
# X = data.iloc[:,[1,2,4,5,6,7,8,9,10]]
# [[2203 2074]
#  [   0    0]]
# X = data.iloc[:,[1,2,4,5,6,7,8,9,10,11]]
# [[2071 2206]
#  [   0    0]]
y = data.iloc[:,[0,-1]]
X.head(5)

HomePlanet CryoSleep   Age    VIP  RoomService  FoodCourt  ShoppingMall  \
0     Europa     False  39.0  False          0.0        0.0           0.0   
1      Earth     False  24.0  False        109.0        9.0          25.0   
2     Europa     False  58.0   True         43.0     3576.0           0.0   
3     Europa     False  33.0  False          0.0     1283.0         371.0   
4      Earth     False  16.0  False        303.0       70.0         151.0   

      Spa  
0     0.0  
1   549.0  
2  6715.0  
3  3329.0  
4   565.0

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
kt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(kt.fit_transform(X))
X

array([[0.0, 1.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 9.0, 25.0, 549.0],
       [0.0, 1.0, 0.0, ..., 3576.0, 0.0, 6715.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 1872.0, 1.0],
       [0.0, 1.0, 0.0, ..., 1049.0, 0.0, 353.0],
       [0.0, 1.0, 0.0, ..., 4688.0, 0.0, 0.0]], dtype=object)

In [28]:

pt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[])],remainder='passthrough')
X=np.array(kt.fit_transform(X))
X

array([[1.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 9.0, 25.0, 549.0],
       [1.0, 0.0, 1.0, ..., 3576.0, 0.0, 6715.0],
       ...,
       [0.0, 1.0, 0.0, ..., 0.0, 1872.0, 1.0],
       [1.0, 0.0, 1.0, ..., 1049.0, 0.0, 353.0],
       [1.0, 0.0, 1.0, ..., 4688.0, 0.0, 0.0]], dtype=object)

In [29]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])

In [30]:
# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression(random_state=0)
# classifier.fit(X,y)

ann = tf.keras.models.Sequential()

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [33]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [34]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
y = sc.transform(y)

c:\Users\sampada jadhav\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


ValueError: X has 2 features, but StandardScaler is expecting 12 features as input.

In [24]:
ann.fit(X, y, batch_size = 32, epochs = 100)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [16]:
testdata = pd.read_csv("test.csv")
testdata = testdata.iloc[:,[1,2,4,5,6,7,8,9,10,11]]
testdata

HomePlanet CryoSleep    Destination   Age    VIP  RoomService  FoodCourt  \
0         Earth      True    TRAPPIST-1e  27.0  False          0.0        0.0   
1         Earth     False    TRAPPIST-1e  19.0  False          0.0        9.0   
2        Europa      True    55 Cancri e  31.0  False          0.0        0.0   
3        Europa     False    TRAPPIST-1e  38.0  False          0.0     6652.0   
4         Earth     False    TRAPPIST-1e  20.0  False         10.0        0.0   
...         ...       ...            ...   ...    ...          ...        ...   
4272      Earth      True    TRAPPIST-1e  34.0  False          0.0        0.0   
4273      Earth     False    TRAPPIST-1e  42.0  False          0.0      847.0   
4274       Mars      True    55 Cancri e   NaN  False          0.0        0.0   
4275     Europa     False            NaN   NaN  False          0.0     2680.0   
4276      Earth      True  PSO J318.5-22  43.0  False          0.0        0.0   

      ShoppingMall     Spa  VRDeck  
0              0.0     0.0     0.0  
1              0.0  2823.0     0.0  
2              0.0     0.0     0.0  
3              0.0   181.0   585.0  
4            635.0     0.0     0.0  
...            ...     ...     ...  
4272           0.0     0.0     0.0  
4273          17.0    10.0   144.0  
4274           0.0     0.0     0.0  
4275           0.0     0.0   523.0  
4276           0.0     0.0     0.0  

[4277 rows x 10 columns]

In [17]:
pt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,2])],remainder='passthrough')
testdata=np.array(pt.fit_transform(testdata))
# tt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[6])],remainder='passthrough')
# testdata = np.array(tt.fit_transform(testdata))
testdata

array([[1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 2823.0, 0.0],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 523.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(testdata[:,:])
testdata[:,:] = imputer.transform(testdata[:,:])
# testdata

In [19]:
y_pred = classifier.predict(testdata)
y_pred

array([ True, False,  True, ...,  True,  True,  True])

In [22]:
xyz = pd.read_csv("sample_submission.csv")
xyz = xyz.iloc[:,0]
xyz

0       0013_01
1       0018_01
2       0019_01
3       0021_01
4       0023_01
         ...   
4272    9266_02
4273    9269_01
4274    9271_01
4275    9273_01
4276    9277_01
Name: PassengerId, Length: 4277, dtype: object

In [21]:
cm = confusion_matrix(xyz, y_pred)
print(cm)

[[2071 2206]
 [   0    0]]


In [23]:
dff = pd.DataFrame(xyz)
dff['Transported'] = y_pred
dff

PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01        False
...          ...          ...
4272     9266_02         True
4273     9269_01        False
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [24]:
dff.to_csv('submission1.csv',index=False)