In [121]:
import matplotlib
import pandas as pd
import numpy as np 
# import matplotlib.pyplot as pt
# import tensorflow as tf


In [122]:
data = pd.read_csv("train.csv")
# X = data.iloc[:,[2,4,5,6,7,8,9,10,11]].values
# [[217  49]
#  [ 55  97]]
X = data.iloc[:,[2,4,5,6,7,9,11]].values
# [[239  27]
#  [  7 145]]
y = data.iloc[:,1].values
X

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [3, 'female', nan, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [123]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
labelencoderX1 = LabelEncoder()
X[:,1] = labelencoderX1.fit_transform(X[:,1])
labelencoderX2 = LabelEncoder()
X[:,-1] = labelencoderX2.fit_transform(X[:,-1])
labelencoderX3 = LabelEncoder()
# X[:,-2] = labelencoderX2.fit_transform(X[:,-2])
labelencoderX4 = LabelEncoder()
# X[:,-4] = labelencoderX2.fit_transform(X[:,-4])
kt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(kt.fit_transform(X))
X

array([[0.0, 1.0, 3, ..., 0, 7.25, 2],
       [1.0, 0.0, 1, ..., 0, 71.2833, 0],
       [1.0, 0.0, 3, ..., 0, 7.925, 2],
       ...,
       [1.0, 0.0, 3, ..., 2, 23.45, 2],
       [0.0, 1.0, 1, ..., 0, 30.0, 0],
       [0.0, 1.0, 3, ..., 0, 7.75, 1]], dtype=object)

In [124]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])
X = np.asarray(X).astype(np.float32)

In [125]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X,y)

# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0)
# classifier.fit(X, y)

# from sklearn.svm import SVR
# regressor = SVR(kernel = 'rbf')
# regressor.fit(X, y)

# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors = 112, metric = 'minkowski', p = 2)
# classifier.fit(X, y)

# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# classifier.fit(X, y)
#23

# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state =10)
# classifier.fit(X, y) 
#0=90 1=89 2=87 4=86 10=85 36=86 10=53 11=59 12=53 

# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
# classifier.fit(X, y)
# #10=0=78 50=1=78 

# from sklearn.cluster import AgglomerativeClustering
# hc = AgglomerativeClustering(n_clusters = 2, affinity = 'euclidean', linkage = 'ward')
# hc.fit(X,y)



c:\Users\sampada jadhav\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [126]:
# ann = tf.keras.models.Sequential()
# ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
# ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
# # ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# # ann.fit(X, y, batch_size = 32, epochs = 100)
# # [[217  49]
# #  [ 55  97]]
# # ann.fit(X, y, batch_size = 32, epochs = 200)
# # 24+4
# ann.fit(X, y, batch_size =20, epochs = 100,verbose=0)
# #0+10
# # 10+4
# # ann.fit(X, y, batch_size = 32, epochs = 400)
# # 43+5


In [127]:
# import keras
# from keras.models import Sequential
# from keras.layers import Dense 

In [128]:

#####only for study

# from sklearn.model_selection import cross_val_score
# from keras.wrappers.scikit_learn import KerasClassifier

# def build_classifier():
#     ann = Sequential()
#     ann.add(Dense(units=5, activation='relu'))
#     ann.add(Dense(units=5, activation='relu'))
#     ann.add(Dense(units=1, activation='sigmoid'))
#     ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#     return ann

# ann = KerasClassifier(build_fn = build_classifier,batch_size = 20, epochs = 100)
# ann.fit(X,y)
    

In [129]:
testdata = pd.read_csv("test.csv")
testdata = testdata.iloc[:,[1,3,4,5,6,8,10]].values
testdata

array([[3, 'male', 34.5, ..., 0, 7.8292, 'Q'],
       [3, 'female', 47.0, ..., 0, 7.0, 'S'],
       [2, 'male', 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       [3, 'male', 38.5, ..., 0, 7.25, 'S'],
       [3, 'male', nan, ..., 0, 8.05, 'S'],
       [3, 'male', nan, ..., 1, 22.3583, 'C']], dtype=object)

In [130]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
labelencoderX1 = LabelEncoder()
testdata[:,1] = labelencoderX1.fit_transform(testdata[:,1])
labelencoderX2 = LabelEncoder()
testdata[:,-1] = labelencoderX2.fit_transform(testdata[:,-1])
labelencoderX3 = LabelEncoder()
# testdata[:,-2] = labelencoderX2.fit_transform(testdata[:,-2])
labelencoderX4 = LabelEncoder()
# testdata[:,-4] = labelencoderX2.fit_transform(testdata[:,-4])
kt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
testdata=np.array(kt.fit_transform(testdata))
testdata

array([[0.0, 1.0, 3, ..., 0, 7.8292, 1],
       [1.0, 0.0, 3, ..., 0, 7.0, 2],
       [0.0, 1.0, 2, ..., 0, 9.6875, 1],
       ...,
       [0.0, 1.0, 3, ..., 0, 7.25, 2],
       [0.0, 1.0, 3, ..., 0, 8.05, 2],
       [0.0, 1.0, 3, ..., 1, 22.3583, 0]], dtype=object)

In [131]:
# pt = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,6])],remainder='passthrough')
# testdata=np.array(pt.fit_transform(testdata))
# testdata

In [132]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(testdata[:,:])
testdata[:,:] = imputer.transform(testdata[:,:])
testdata
testdata = np.asarray(testdata).astype(np.float32)

In [133]:
# X = X[:,1:]
# testdata = testdata[:,1:]

In [134]:
# def boolstr_to_floatstr(v):
#     if v == 'True':
#         return '1'
#     elif v == 'False':
#         return '0'
#     else:
#         return v

In [135]:
y_pred=classifier.predict(testdata)

In [136]:
# features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
# from sklearn.preprocessing import OneHotEncoder
# oneh = OneHotEncoder(handle_unknown="ignore")
# oneh.fit(X)
# X_test = oneh.transform(testdata)

# import math
# for i in range(0,418):
#     y_pred[i]=int(math.floor(y_pred[i]+0.5))

# y_pred = ann.predict(testdata)
# y_pred = (y_pred>0.5)
# y_pred = np.vectorize(boolstr_to_floatstr)(y_pred).astype(int)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [137]:
xyz = pd.read_csv("gender_submissions.csv")
xyz = xyz.iloc[:,1]
xyz

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [138]:
# testdata.reshape(len(testdata),1)

In [139]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(xyz, y_pred)
print(cm)

[[253  13]
 [  8 144]]


In [140]:
# dff = pd.DataFrame(xyz)
# dff['Survived'] = y_pred
# dff

In [141]:
# dff.to_csv('gender_submission.csv',index=False)